apiVersion: v1
kind: Secret
metadata:
  name: stocks-analyst-secrets
  labels:
    app: stocks-analyst
type: Opaque
data:
  # Base64 encoded values for Snowflake connection
  SNOWFLAKE_USER: YOUR_BASE64_USER
  SNOWFLAKE_PASSWORD: YOUR_BASE64_PASSWORD
  SNOWFLAKE_ACCOUNT: YOUR_BASE64_ACCOUNT
